### ISSUE TITLE
Publishing tag input has UX issues

### ISSUE THREAD

**Issue by rabbit** [AkashaProject/Alpha#10]
## Summary

The tag input field when publishing content has a few UX issues I will group together here. The third item is purely a recommendation.

1. unenclosed tags (user types input but has yet to hit spacebar to enclose tag) will be cleared if the user presses the tab key. instead, tab key should only move to next input if there are no unenclosed tags left to enclose.
2. typing a long tag name makes text invisible as it's hidden in the boundary of the tag input. (ie: typing "something" will only show "omething" as the "s" is moved out of view). since the user can't see the boundary of the tag input, it appears letters are deleted.
3. it's not immediately obvious why unpublished tags are given a special appearance with a plus sign. I recommend adding a new form field immediately below the tag input when new tags are detected to collect and list the unpublished tags with information for the user to publish them.

**Comment by MihaiAlisie** [comment]
Working on it, improvements will be introduced in the 0.3.0 release scheduled for next week.

Cheers!

**Comment by bogdanbrezuica** [comment]
@rabbit Hi there! Can you please check the tag input field in 0.3.0 version and maybe give some extra feedback or close this issue? 

Items 1) and 2) from above should be fixed. Regarding the third item, we are still thinking about how to make the process of adding a tag more user-friendly.

And, of course, thanks for your help!

**Comment by rabbit** [comment]
Excellent! I like the way this feels. 💅
