### ISSUE TITLE
Unable to log in or import identity

### ISSUE THREAD

**Issue by somanyquestions** [AkashaProject/Alpha#107]
Hi!

I've just got a new pc (Windows pioneer) and downloaded Akasha. I'm unable to log in or import my profile established on my old computer. The program is fully synchronized. Please help.

Thanks and kind regards,
Hilary

**Comment by somanyquestions** [comment]
[Akasha Import Existing Identity screen shot.pptx](https://github.com/AkashaProject/Alpha/files/1064208/Akasha.Import.Existing.Identity.screen.shot.pptx)

Hi Team,

I'm still not able to either LogIn to my existing account or import my profile. When I hover my mouse over LogIn (top left of screen), there's nothing to click on. I'm unable to proceed with the option to import an identity for simlar reasons.

I have a proposal to research the Akasha Project for the Blockchain Research Institute www.blockchainresearchinstitute.org. I'd love to import my profile from an old PC onto a new one to get going on this machine. Otherwise if this isn't manageable I'll have to create a new identity (but I really like my old one since it's just my first name "hilary".

Thanks - please let me know if this is possible in the immediate term. Hope to connect with the team leadership on my research project shortly afterwards for an interview.

**Comment by SeverS** [comment]
Hey @somanyquestions !
On your old computer, find your AKASHA Key file in `C:/Users/%Your username%/AppData/Roaming/Ethereum/akasha-alpha/keystore`;
Copy the file(s) in the same directory on your newer computer.
Now start AKASHA.

> NOTE: It is possible to not be able to see all your profile data because they are on the old computer. However, you can leave your old PC with AKASHA running until the data is transferred or you can edit your profile and re-add that data.

**Comment by somanyquestions** [comment]
Hi Sever,
Thanks for getting back to me. I'm unable copy the file from the directory. Here's what the file looks like int the screen shot (doesn't really have a recognizable format and Windows makes suggestions that aren't relevant).
Thanks - willing to keep trying!
Kind regards,
Hilary
![unable to copy files](https://user-images.githubusercontent.com/26461264/27016415-989381e6-4eed-11e7-8932-da74b2c36d07.png)

**Comment by SeverS** [comment]
@somanyquestions you don't need to open it, just copy it to the same folder on your newer computer

**Comment by somanyquestions** [comment]
Hi Sever,

Congratulations on your rock star achievements in the development of AKASHA! I've just finished a written report on the network, about 5000 words, and it's been such a privilege to have had this window of insight into the future.

Not unrelated to my questions above, I moved from a PC to a MAC some time ago - would like to import my original AKASHA ID from an old PC because my profile name is just "hilary" and I think that would be pretty cool. Please let me know how the process works when moving from PC to MAC - I know where to find my ID on the PC but not sure about importing to MAC. Possible?

Many thanks!
Hilary
