### ISSUE TITLE
Unable to create identity

### ISSUE THREAD

**Issue by Ike-Pono** [AkashaProject/Alpha#109]
Unable to proceed after entering information to create account. Get the message below.

Your identity is broadcasted into the AKASHA private network.

This will take a few moments ...
Current Status:Receiving aethers from AKASHA
RFFE01

**Comment by gregberns** [comment]
+1

**Comment by joshmcbride** [comment]
+1

**Comment by pauljonas** [comment]
+1

**Comment by pauljonas** [comment]
precisely :+1: 
"Your identity is broadcasted into the AKASHA private network.
This will take a few moments ...
Current Status:Creating local Ethereum key
RFFE01"

**Comment by pauljonas** [comment]
if I click "Retry step" at this point 
"Your identity is broadcasted into the AKASHA private network.
This will take a few moments ...
Current Status:Receiving aethers from AKASHA
RFFE01"

**Comment by amarjeet000** [comment]
+1

**Comment by vannordwand** [comment]
+1

**Comment by MihaiAlisie** [comment]
Thanks everyone for drawing our attention to this issue! 😅 

We will look into it and post an update here when fixed! 👍

**Comment by tagoreghanta** [comment]
+1, will wait for the fix

**Comment by MihaiAlisie** [comment]
Hey everyone,

Can you please give it another try now and tell us if everything works ok?

Big thanks go to @kenshyx for the quick response and fix - **on a Sunday**! 🥇

**Comment by amarjeet000** [comment]
Working for me now

**Comment by vannordwand** [comment]
too cool, works like a charm now. Thanks for the extra mile on Sunday! (y)

**Comment by tagoreghanta** [comment]
Erroring with 
"SGE01geth: exited with code: 1"

info
14:01:50
geth:spawn:close: 1

error
14:01:50
geth: exited with code: 1

error
14:01:50
geth: exited with code: 1

info
14:01:50
I0604 14:01:50.760695 p2p/server.go:340] Starting Server

info
14:01:50
I0604 14:01:50.759672 eth/handler.go:119] blockchain not empty, fast sync disabled

info
14:01:50
I0604 14:01:50.758690 core/blockchain.go:219] Last header: #1016499 [c7903a2c…] TD=1382042778681 I0604 14:01:50.758690 core/blockchain.go:220] Last block: #1016499 [c7903a2c…] TD=1382042778681 I0604 14:01:50.758690 core/blockchain.go:221] Fast block: #1016499 [c7903a2c…] TD=1382042778681

**Comment by tagoreghanta** [comment]
hi All,
Worked for me too 

Thanks
