### ISSUE TITLE
IPFS does not start on Mac OS X

### ISSUE THREAD

**Issue by jbrukh** [AkashaProject/Alpha#11]
Max OS 10.10.5.

Cannot turn on IPFS manually (control is disabled):

<img width="1279" alt="screen shot 2016-12-25 at 8 12 02 pm" src="https://cloud.githubusercontent.com/assets/44650/21473567/979bc49e-cade-11e6-8657-3230011908e7.png">

Next button is disabled:

<img width="1286" alt="screen shot 2016-12-25 at 8 12 07 pm" src="https://cloud.githubusercontent.com/assets/44650/21473568/97a8ae02-cade-11e6-877d-bbf2abad4dbe.png">

May or may not have to do with the fact that I have some old IPFS on my system, probably. Any ideas appreciated.

**Comment by jbrukh** [comment]
Fixed this by reseting the IPFS directory and restarting.

**Comment by MihaiAlisie** [comment]
We'll get this one into our FAQ - thanks for reporting also the solution!

Cheers!
