### ISSUE TITLE
SIE01Cannot start IPFS service. Check logs for more details.

### ISSUE THREAD

**Issue by CampingScorpion** [AkashaProject/Alpha#110]
Downloaded AKASHA-macosx-0.5.2.dmg and during the "express" install saw the below:

<img width="518" alt="screen shot 2017-06-04 at 1 52 51 am" src="https://cloud.githubusercontent.com/assets/45647/26759321/a47b4db6-48c8-11e7-8108-cc9cb98d4afd.png">

I'm pretty sure my install is just stuck now. Let me know where the logs are, and I'll try to get you guys more info.

**Comment by CampingScorpion** [comment]
anyone home? :D

**Comment by hrishinext** [comment]
Did you continue to get this error post quitting and restarting? I am
curious.

**Comment by HuangFJ** [comment]
could you state the logs?

**Comment by canopussy** [comment]
same problem...uninstalled that crap
