### ISSUE TITLE
Feature Request: Tags

### ISSUE THREAD

**Issue by anathaniel82** [AkashaProject/Alpha#112]
Hi team,
Thanks for the great job on Akasha. I've been posting my Blockchain/Bitcoin articles on the platform. Re the tags available, I urge you to allow multiple word tags and shorter tags as well. for instance I was unable to create a tag for ICO (because of length) and even Venture Capital or Private Equity. It would be great if you could allow shorter tags and multiple words.

Sincerely,

Ajit.

**Comment by SeverS** [comment]
Hello @anathaniel82

Thanks for the suggestions!
In the next release we'll lower the minimum number of characters for tags to 2. 
Multiple word tags it's not possible atm.

Do you use AKASHA's editor for writing your articles or just copy/paste them from other documents?
I'm curious if you like the editor. Any suggestions? :D

Thanks,
Sever

**Comment by anathaniel82** [comment]
Hi Sever,
Thanks for your response. I currently copy and paste my content into
Akasha's editor. Akasha is not currently my primary blog. I write in
Microsoft Word and then use WordPress or LinkedIn to publish. For now,
that's my process. Of course if I get more traction on Akasha, I shall
consider using it actively.

Regards,

Ajit Nathaniel
----------------------
www.zudik.com
----------------------
This Email was sent from a mobile device. Brevity is a consequence of this
convenience, so pardon me for not being my typically verbose self.
