### ISSUE TITLE
Option to increase chain size?

### ISSUE THREAD

**Issue by spaasis** [AkashaProject/Alpha#114]
(I have very little knowledge of the technology used here, so this might not make any sense)

I was wondering if you could add an option to increase the IPFS volume? I have a lot of spare disk space, and wouldn't mind using it to store more of the chain. Would this also speed up the network, or at least reduce the times people see the "no nodes available"-error?

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#289
