### ISSUE TITLE
After installing Akasha, Mist opens private-net

### ISSUE THREAD

**Issue by Nomadjackalope** [AkashaProject/Alpha#116]
Tried `geth --networkid 1` and `mist --network main` separately and together but nothing changes it.

How do I get Mist back to main network?

**Comment by SeverS** [comment]
Hello @Nomadjackalope 
Sorry for the delay
Did you solved the issue with Mist?

**Comment by Nomadjackalope** [comment]
No worries. I can get it to work if I rename my chaindata folder to chaindataBACKUP. In essence, I'm clearing it. But I would really rather not download that again.

I also tried moving the MANIFEST-xxxxxx file out of the chaindata folder but it didn't get remade automatically and geth wouldn't run without it.

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#286
