### ISSUE TITLE
Akasha Login from Mac to Windows 10

### ISSUE THREAD

**Issue by msanmiguel21** [AkashaProject/Alpha#117]
I am trying to import an existing profile from my mac computer to my new desktop - Windows 10, but it seems there isn't an option for that. The only option I see is "create new identity", regardless of the fact that is mentions "No profiles found. Create a new identity or import an existing one."

How can this be done?

**Comment by SeverS** [comment]
Hey msanmiguel21, 
Did you tried this? https://github.com/AkashaProject/Alpha/wiki/FAQ#how-can-i-backup-my-identity-andor-port-it-to-another-machine

**Comment by msanmiguel21** [comment]
Hi there,

I’ve tried the suggested and still doesn’t work. I did this via command line and via the directory folder. I’ve found my key, but cannot figure out how to input it into the directory. Does is need to be a certain file type?

Please help. 

Thanks,
-Mickey S. 

Valdemar (Mickey) San Miguel
Configuration Management Analyst

**Comment by SeverS** [comment]
Hello @msanmiguel21
>  I’ve found my key

Great. You just need to copy it to your windows machine in 
`C:/Users/%Your username%/AppData/Roaming/Ethereum/akasha-alpha/keystore` folder.

> Does is need to be a certain file type?

Do not change the file type. Leave it as it is.

After that open AKASHA, or hit refresh (ctrl+r).

Also check #107

**Comment by SeverS** [comment]
#107

**Comment by msanmiguel21** [comment]
Did all of the below mentioned and still cannot see my profile. Attached is a picture of the new directory, but still no profile on my Akasha account…Please help!

Thanks,
-Mickey S. 

Valdemar (Mickey) San Miguel
Configuration Management Analyst

**Comment by SeverS** [comment]
Can't see any picture. Did you attached it?

**Comment by msanmiguel21** [comment]
Thanks,
-Mickey S. 

Valdemar (Mickey) San Miguel
Configuration Management Analyst

From: Mickey San Miguel
Sent: Friday, June 23, 2017 6:44 PM
To: AkashaProject/Alpha; AkashaProject/Alpha
Cc: Mention
Subject: RE: [AkashaProject/Alpha] Akasha Login from Mac to Windows 10 (#117)

Did all of the below mentioned and still cannot see my profile. Attached is a picture of the new directory, but still no profile on my Akasha account…Please help!

Thanks,
-Mickey S. 

Valdemar (Mickey) San Miguel
Configuration Management Analyst

**Comment by msanmiguel21** [comment]
Hi,

I really would like to keep my account and not resort to creating another.
Do you perhaps have a short video that demonstrates the action taken.

Please help.

Thanks,
Mickey S.

**Comment by SeverS** [comment]
Hey Mikey,
I thought you figured out how to port your identity.
I don't have a video for this but basically the steps are:
- on mac:
    1. copy your eth key file from `~/Users/%Your Username%/Library/Ethereum/akasha-alpha/keystore` to a usb stick or something (name of the key should start with something like `UTC--`)

- on Windows (after you have installed AKASHA and synchronized):
    1. copy the file from your usb drive to `C:/Users/%Your Username%/AppData/Roaming/Ethereum/akasha-alpha/keystore`

Now start/restart AKASHA and you'll be able to see your profile.

Thanks,
Sever

**Comment by msanmiguel21** [comment]
Copied file from MacBook > to USB > Uploaded to Windows as shown below:
![usb](https://user-images.githubusercontent.com/17679840/27757698-266d9b7c-5dc2-11e7-9eb3-7a3f21ca641d.PNG)

Moved file from USB > to path shown above > File existed in folder. 
![folder](https://user-images.githubusercontent.com/17679840/27757699-28d0e1ee-5dc2-11e7-92e7-42f0dbdb9c67.PNG)

I restart Akasha & existing profile still doesn't show:
![akasha](https://user-images.githubusercontent.com/17679840/27757760-08d42b70-5dc3-11e7-851a-e51c050cebc8.PNG)

Have there been any successful transfers? Please tell me there is a way ;-)

Thanks,
Mickey

**Comment by SeverS** [comment]
Hello Mikey,
Can you tell me what's your AKASHA id (username)? The one you have registered with.

Thanks,
Sever

**Comment by msanmiguel21** [comment]
Hi Sever,

Of course, it's  @**gonrogue**

Regards,
Mickey S.

**Comment by SeverS** [comment]
Hi Mikey,

We've checked and that key is not associated with your AKASHA id.
Please check `~/Users/%Your Username%/Library/Ethereum/akasha-alpha/keystore` **on your Mac** again and find a key starting with `UTC--%some date%--f79b8e60b38...`.

Thanks,
Sever
