### ISSUE TITLE
Ubuntu 16.04 + Ethereum Wallet + Akasha don't let me choose geth folder

### ISSUE THREAD

**Issue by rarigita** [AkashaProject/Alpha#119]
When I open Akasha the first time it ask for simple or advanced setup. I already have the Ethereum wallet, so I go for the advanced setup and click to change the geth path. Then it freezes all times I try, I can only kill the app to try again. No luck so far. I don't want to have another instance of geth on the system. Any help...?

**Comment by SeverS** [comment]
Hey @tantosoft 
Thank you for reporting this. We'll look into this and fix it in the next release.
Meanwhile you can try `express setup` as it will not interfere with the existing chain (it will create a separate folder for AKASHA's private chain).

Thanks

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#280
