### ISSUE TITLE
Separate ipfs node for Akasha?

### ISSUE THREAD

**Issue by JayBrown** [AkashaProject/Alpha#120]
Currently I have to stop the ipfs daemon of my primary node before launching Akasha. The app then runs its own daemon using ~/Library/Application\ Support/AKASHA/ipfs, but it still uses my primary node's ipfs storage directory. Wouldn't it be better for Akasha to create its own node? Or just to "hop onto" an existing node/daemon?

This is also important, because Akasha uses v0.4.6 of the ipfs binary, whereas the current version is already at 0.4.10. Several newly implemented hashes are not compatible with older versions like 0.4.6.

**Comment by JayBrown** [comment]
I just removed Akasha's 0.4.6 ipfs binary, and replaced it with the current 0.4.10, and Akasha seems to run fine. (For now.) But a separate Akasha-node would be preferable.

**Comment by ravibhojwani** [comment]
Good work .

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#279
