### ISSUE TITLE
Must allow first names with only two characters

### ISSUE THREAD

**Issue by JayBrown** [AkashaProject/Alpha#121]
There are so many first names, nicknames & first+second name contractions with only two letters; AKASHA **_must_** allow users to use their actual names if they are e.g. Bo, AJ, JJ, Mo, Ty, Jo etc.

**Comment by SeverS** [comment]
Hey @JayBrown ,
Noted. Starting from next release we'll allow two letters first/second names.

Thanks for suggestions!
Sever

**Comment by JayBrown** [comment]
Other users should chime in, because there might even be one-letter first & last names. Not in English, of course (except with pseudonyms like "Mr. T"), but in other languages… Vietnamese maybe? But I can't answer that.

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#278
