### ISSUE TITLE
Reading comments -> back to entries

### ISSUE THREAD

**Issue by grewqas** [AkashaProject/Alpha#122]
While scrolling down the stream line, you open comments for an entry and then click close, you start from the very top of the line again. So you need to scroll down again to the place you were before, which makes it quite annoying.

**Comment by bogdanbrezuica** [comment]
Hello @grewqas

Thanks for the feedback! We are aware of this inconvenience and the next release will bring a big improvement. Please bear with us until then :)

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#277
