### ISSUE TITLE
FAQ, mac os file path

### ISSUE THREAD

**Issue by stupidusernametoreportissues** [AkashaProject/Alpha#124]
On Mac ~/Users/%Your Username%/Library/Ethereum/akasha-alpha/geth/chaindata
should read
~/Library/Ethereum/akasha-alpha/geth/chaindata
or
/Users/%Your Username%/Library/Ethereum/akasha-alpha/geth/chaindata

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#275
