### ISSUE TITLE
Link to slack channel broken

### ISSUE THREAD

**Issue by snibbe** [AkashaProject/Alpha#125]
https://akasha-slack.herokuapp.com returns an application error:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by rychardemanne** [comment]
Yes, that link is broken and the other Slack channel requires a password/invitation.

**Comment by thowar2** [comment]
How can I join slack?

**Comment by dsky1990** [comment]
How can I join slack?

**Comment by subodubo** [comment]
I was wondering the same thing, if possible to get slack invitation.

**Comment by 42piratas** [comment]
Hey all!

I'm sorry for the very late reply.

You can join us on [our official Discord channel](https://discord.gg/JqqKasJ).

Thanks for getting in touch! Cheers!
