### ISSUE TITLE
Alpha rewards and economic algorithm

### ISSUE THREAD

**Issue by rychardemanne** [AkashaProject/Alpha#127]
Some questions

Is Akasha Alpha being monitored? It needs someone to motivate discussions as impossible to gauge the rewards system without votes and interactions.

Is there any published details of the rewards system and the economic model within Akasha? I have some recent experience in this.

I know this is mainly for bugs and coding issues, but the conceptual framework comes first.

regards
RM

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#272
