### ISSUE TITLE
No explanation for the "Claim on Ethereum" link

### ISSUE THREAD

**Issue by RMBLRX** [AkashaProject/Alpha#128]
I don't think it's totally clear what that ethereum icon at the bottom of a user's own posts does until clicked on.  Not knowing, I clicked on it to see, and now my post cannot accept up or down votes since it ends the voting period.  It seems to me that that's pretty big commitment, considering that I cannot delete the post (or at least somehow orphan it, removing it from my profile and perhaps re-posting it), so some sort of explanation and confirmation when the icon is clicked would be wonderful.

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#273
