### ISSUE TITLE
Long-form and Iterative Authorship

### ISSUE THREAD

**Issue by RMBLRX** [AkashaProject/Alpha#129]
One of the potential use cases that I had in mind when I first encountered Akasha was to publish serial fiction.  However, after seeing how it actually worked, I am incredibly disinclined to do so for a few reasons:

- the permanence of ending a post's "voting period" #128, as i'm uncertain that the utility of this jives with the nature of more literary modes of publishing.
- the inability to edit a work indefinitely, as typos or stylistic blemishes are permanent and permanently attributed to the author, making posting... anything at all really... a rather intimidating endeavor.
- the inability to receive inline feedback on a post's content, à la Medium (for crowd-sourcing editing and engaging with one's audience).
- the lack of a rich or full-featured editing and or publishing environment (or at the very least, making Akasha editor-agnostic but with a reasonable level of HTML support via markdown and the like).

It seems to me that Akasha is uniquely positioned to alleviate any or all of these concerns through its use of IPFS, as it can readily archive iterations of a post, assuming that posting is done under an IPNS hash, rather than just an IPFS hash.  I could, for instance, imagine that votes and comments could also somehow be attributed to a given draft of the post in the archive (whereas drafts with no votes or comments would eventually fade away unless otherwise somehow pinned, I guess).

I think that what I'd really like to see with Akasha is something like Medium in terms of the social or curational side of things and something like [Draft](https://draftin.com) on the editing and publishing side of things (specifically in terms of versioning).  I think that if Akasha is going to be at the vanguard of social blogging, it needs to do its utmost to facilitate quality and substantial content.

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#274
