### ISSUE TITLE
Text editor drag & drop is not functional

### ISSUE THREAD

**Issue by tofugarden** [AkashaProject/Alpha#132]
Dropping text between words causes some unexpected behavior:

- Selected text doesn't drop where the cursor is. Ether in the middle of a word or one word after.
- When dragging and dropping between paragraphs, typing causes the cursor to return where text was last dropped. Only way back is to undo.

To reproduce: try to drag & drop within a line, and then between paragraphs.

Akasha 0.5.2; Ubuntu Gnome 17.04.

**Comment by 42piratas** [comment]
Hey @crichez!

First, I'm sorry for the late reply. 

I'm closing this issue as it seems to be solved in the latest beta. But if you still see any problem in the latest beta, please let me know in the repo `/dapp` and I'll check asap.

Thank you very much for your feedback! We appreciate your contribution. 

Cheers!
