### ISSUE TITLE
Search service is not available at the moment

### ISSUE THREAD

**Issue by shapiroz** [AkashaProject/Alpha#133]
"Search service is not available at the moment"
![image](https://user-images.githubusercontent.com/28999526/31193973-502199c8-a94e-11e7-91e3-6f2b9b2bbe41.png)

**Comment by 42piratas** [comment]
Hey @shapiroz 

First, I'm sorry for the late reply. 

I'm closing this issue as it seems to be solved in the latest beta. But if you still see any problem in the latest beta, please let me know in the repo `/dapp` and I'll check asap.

Thank you very much for your feedback! We appreciate your contribution. 

Cheers!
