### ISSUE TITLE
identity not found

### ISSUE THREAD

**Issue by somanyquestions** [AkashaProject/Alpha#134]
Hi!
Akasha is asking me to create a new identity. I've sent up two already - one on a PC and another on a MAC. I had to reload Akasha on the MAC and can't get the old identity. I can't log into my profiles (hovering over the words "log in" does not create fuctionality). Should I start over?

**Comment by bogdanbrezuica** [comment]
hello!
have you tried [this](https://github.com/AkashaProject/Alpha/wiki/FAQ#how-can-i-backup-my-identity-andor-port-it-to-another-machine)?

**Comment by 42piratas** [comment]
Hello @somanyquestions 

I'm closing this issue as it seems to be solved.

Thank you very much for your feedback! We appreciate your contribution.

Cheers!
