### ISSUE TITLE
Cannot add tags in Akasha

### ISSUE THREAD

**Issue by Xstelar19** [AkashaProject/Alpha#135]
WhenI add a tag in Akasha I get the message "You must at least add 1 valid tag".  #Freedomofspeech is a tag I have used before.

**Comment by 42piratas** [comment]
Hey @gbatistaart!

I'm sorry for the late reply. 

I'm closing this issue as it seems to be solved in the latest beta.

Thank you very much for your feedback! We appreciate your contribution. 

Cheers!
