### ISSUE TITLE
Akasha Version 0.5.2 - Plse Help with Error "RFF01 - read ECONNRESET"

### ISSUE THREAD

**Issue by KingLion777** [AkashaProject/Alpha#137]
Dear Akasha Team,

I have downloaded Akasha version 0.5.2 and have trouble moving beyond this point as in the screenshot below.

It shows the error: "RFFE01 - read ECONNRESET"

<img width="960" alt="2017-11-16 3" src="https://user-images.githubusercontent.com/32773472/32884783-2553aec4-cac4-11e7-967d-6ec8b2f51b83.png">

Please help me to get this rectified and to move on to experiment in using your niche product.

Thank you very much.

G.

**Comment by 42piratas** [comment]
Hey @KingLion777!

First, I'm sorry for the late reply. 

I'm closing this issue as it seems to be solved in the latest beta. But if you still see any problem in the latest beta, please let me know and I'll check asap.

Thank you very much for your feedback! We appreciate your contribution. 

Cheers!
