### ISSUE TITLE
Akasha Syn error

### ISSUE THREAD

**Issue by arbeitdonq** [AkashaProject/Alpha#138]
07:57:50
connection to ipc Established!

info
07:57:50
I0116 07:57:50.915883 p2p/server.go:608] Listening on [::]:30303 I0116 07:57:50.916713 node/node.go:341] IPC endpoint opened: /Users/trevoroutten2/Library/Ethereum/akasha-alpha/geth.ipc

info
07:57:50
I0116 07:57:50.913089 p2p/discover/udp.go:227] Listening, enode://7a2bfb345c30348796bf6b16095e490d5cb01c0816e9c7db1778a45f603cfed6884ccf31f0d691a8145cf2cbad887e622508293c401ca0d6e2c1d9f1413ce4e4@95.33.85.224:30303 I0116 07:57:50.913401 whisper/whisperv2/whisper.go:176] Whisper started

info
07:57:48
I0116 07:57:48.753054 p2p/server.go:340] Starting Server

info
07:57:48
I0116 07:57:48.750569 core/blockchain.go:219] Last header: #0 [6577484f…] TD=131072 I0116 07:57:48.750602 core/blockchain.go:220] Last block: #0 [6577484f…] TD=131072 I0116 07:57:48.750620 core/blockchain.go:221] Fast block: #0 [6577484f…] TD=131072

info
07:57:48
I0116 07:57:48.749389 eth/backend.go:215] Chain config: {ChainID: 0 Homestead: 10 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: <nil> EIP158: <nil>}

info
07:57:48
I0116 07:57:48.747738 eth/backend.go:187] Protocol Versions: [63 62], Network Id: 511337

info
07:57:48
I0116 07:57:48.417750 node/node.go:176] instance: Geth/v1.5.9-stable-a07539fb/darwin/go1.7.4 I0116 07:57:48.417827 ethdb/database.go:83] Allotted 512MB cache and 1024 file handles to /Users/xxxxxxxxxxxLibrary/Ethereum/akasha-alpha/geth/chaindata

info
07:57:48
I0116 07:57:48.393119 ethdb/database.go:176] closed db:/Users/xxxxxxxxxx/Library/Ethereum/akasha-alpha/geth/chaindata

info
07:57:48
I0116 07:57:48.376184 cmd/utils/flags.go:613] WARNING: No etherbase set and no accounts found as default I0116 07:57:48.376349 ethdb/database.go:83] Allotted 512MB cache and 1024 file handles to /Users/xxxxxxxxxx/Library/Ethereum/akasha-alpha/geth/chaindata

info
07:57:48

Please advise and thank you for your time.

**Comment by bogdanbrezuica** [comment]
hello @arbeitdonq . The alpha version is no longer supported. You can register for the beta version [here](https://akasha.world/) and wait for an invite.

**Comment by arbeitdonq** [comment]
Thank you.
