### ISSUE TITLE
UI is counter intuitive

### ISSUE THREAD

**Issue by bitcloudTheFirst** [AkashaProject/Alpha#14]
A shortlist:

1) All buttons are mystery meat
2) Some buttons are greyed out mystery meat. (The search button for example)
Hover doesn't work consistently.
3) Creating a status is a three step operation

Basically it means that no one knows what they're doing, meant to do, or can do.

Also, I'll put it out there that a new user is going to be immediately stressed out by the notion that following someone is "Spending gas"... everything about this analogy is off. Gas has a negative connotation, and using it induces FOMO.

"Are you sure you want to comment?"
This isn't going to work like this. The user clicked comment, so they are sure.

**Comment by MihaiAlisie** [comment]
Hi there,

First of all, thank you for taking the time to test AKASHA!

> All buttons are mystery meat

Less mysterious but more constructive feedback would be fantastic :) Help us to help you!

> Some buttons are greyed out mystery meat.

When hovering over the greyed out buttons you should see a "coming soon" tooltip. The `hover over tooltip` component used is behaving tricky indeed and we're looking into ways to make it work consistently across all operating systems in the next releases.

> Creating a status is a three step operation

Things will get better in the next releases and an option to quickly create a status will be introduced soon.

> Basically it means that no one knows 

Surprisingly enough, the majority of people figured out things quickly which tends to contradict your "counter intuitive" argument. That being said, I agree that things are not by any means "perfect" and we'll continue to polish things as we progress. Keep in mind, however, that this is an **alpha pre-release** and that this sort of **problems are normal and expected**.

> "Spending gas"... everything about this analogy is off. Gas has a negative connotation, and using it induces FOMO.

Unfortunately, this is an inherited problem from Ethereum and we are thinking on ways to improve the user experience for those that are not familiar with Ethereum and/or the concept of "gas". In other words, we are aware of this problem and improvements on this side are to be expected.

In the meantime, if you're interested in learning what Ethereum gas is and how it works I recommend watching this video https://www.youtube.com/watch?v=dd-ajiMl4HY

> "Are you sure you want to comment?" (...) The user clicked comment, so they are sure.

We will streamline the various gas confirmations in the 0.3.0 release scheduled for next week as a first step towards improving the user experience in this regard.
