### ISSUE TITLE
Stuck on finding peers

### ISSUE THREAD

**Issue by k00ki** [AkashaProject/Alpha#147]
I'm using Win7 and Akasha 0.5.2
It's always stuck on finding peers. couldn't go to the next step.

17:43:36
connection to ipc Established!

info
17:43:36
I0130 17:43:36.326113 node/node.go:341] IPC endpoint opened: \\.\pipe\C:\Users\xx\AppData\Roaming\Ethereum\akasha-alpha\geth.ipc

info
17:43:36
I0130 17:43:36.325113 p2p/server.go:608] Listening on [::]:30303

info
17:43:36
I0130 17:43:36.325113 whisper/whisperv2/whisper.go:176] Whisper started

info
17:43:36
I0130 17:43:36.318112 p2p/discover/udp.go:227] Listening, enode://8f5e731f1ea168ae37c3ca1d6c3ae9c51a246b3cb7031dd0499b3683db31b1459dda6de38dbc2ad17007987da2ee3e5f9cbba5461c2b5d2311d10e671aba764a@0.0.0.0:30303

info
17:43:34
I0130 17:43:34.188900 p2p/server.go:340] Starting Server

info
17:43:34
I0130 17:43:34.186899 core/blockchain.go:219] Last header: #0 [6577484f…] TD=131072 I0130 17:43:34.186899 core/blockchain.go:220] Last block: #0 [6577484f…] TD=131072 I0130 17:43:34.186899 core/blockchain.go:221] Fast block: #0 [6577484f…] TD=131072

info
17:43:34
I0130 17:43:34.186899 eth/backend.go:215] Chain config: {ChainID: 0 Homestead: 10 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: <nil> EIP158: <nil>}

info
17:43:34
I0130 17:43:34.185899 eth/backend.go:187] Protocol Versions: [63 62], Network Id: 511337

info
17:43:34
I0130 17:43:34.078889 ethdb/database.go:83] Allotted 512MB cache and 1024 file handles to C:\Users\xx\AppData\Roaming\Ethereum\akasha-alpha\geth\chaindata

info
17:43:34
I0130 17:43:34.078889 node/node.go:176] instance: Geth/v1.5.9-stable/windows/go1.7.4

info
17:43:34
I0130 17:43:34.075888 ethdb/database.go:176] closed db:C:\Users\xx\AppData\Roaming\Ethereum\akasha-alpha\geth\chaindata

info
17:43:34
I0130 17:43:34.031884 cmd/utils/flags.go:613] WARNING: No etherbase set and no accounts found as default I0130 17:43:34.031884 ethdb/database.go:83] Allotted 512MB cache and 1024 file handles to C:\Users\xx\AppData\Roaming\Ethereum\akasha-alpha\geth\chaindata

info
17:43:34
I0130 17:43:33.862867 node/config.go:445] Failed to start Ledger hub, disabling: libusb: not found [code -5]

**Comment by staberas** [comment]
Same problem

**Comment by kenshyx** [comment]
The alpha version is no longer maintained. This is the latest release https://github.com/AkashaProject/dapp/releases/tag/0.6.2
