### ISSUE TITLE
New Identity Creation (Last Name)

### ISSUE THREAD

**Issue by techamazed** [AkashaProject/Alpha#15]
Last Name must be at least 3 characters long. My last name only 2 characters long and I am sure that there are many other people whose last name could be less than 3 characters....

**Comment by MihaiAlisie** [comment]
Hello and thank you for testing AKASHA!

👯 This will be fixed in the next release (0.3.0) 👯

**Comment by SeverS** [comment]
Starting from 0.3.0 last name is optional.
Thanks for suggestions 😺
