### ISSUE TITLE
Error code EUE01

### ISSUE THREAD

**Issue by NSamii** [AkashaProject/Alpha#152]
Got this pop-up when I tried to upvote an article. Transaction still on pending.

Don't know if this log is helpful but here it is.

"ERROR
12:50:01
[0;37m12:50:01.335 [31mERROR [0;34m floodsub: [0merror reading rpc from <peer.ID XSSkeN>: connection reset [0;37mcomm.go:36[0m

ERROR
12:48:42
[0;37m12:48:42.191 [31mERROR [0;34m floodsub: [0merror reading rpc from <peer.ID Vn3Kwt>: connection reset [0;37mcomm.go:36[0m

ERROR
12:43:55
[0;37m12:43:55.898 [31mERROR [0;34m floodsub: [0merror reading rpc from <peer.ID W5P8PZ>: connection reset [0;37mcomm.go:36[0m

ERROR
12:43:33
[0;37m12:43:33.007 [31mERROR [0;34m floodsub: [0merror reading rpc from <peer.ID TWnFHp>: connection reset [0;37mcomm.go:36[0m

ERROR
12:42:40
[0;37m12:42:40.010 [31mERROR [0;34m bitswap: [0mcouldnt open sender again after SendMsg(<peer.ID cqQ7Ge>) failed: dial attempt failed: context deadline exceeded [0;37mwantmanager.go:237[0m

ERROR
12:42:39
[0;37m12:42:39.599 [31mERROR [0;34m bitswap: [0mcouldnt open sender again after SendMsg(<peer.ID dsnZhr>) failed: dial attempt failed: context deadline exceeded [0;37mwantmanager.go:237[0m

ERROR
12:42:29
[0;37m12:42:29.130 [31mERROR [0;34m bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m

ERROR
12:40:46
[0;37m12:40:46.687 [31mERROR [0;34m bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m

ERROR
12:40:00
[0;37m12:40:00.180 [31mERROR [0;34m floodsub: [0merror reading rpc from <peer.ID ZiPRod>: connection reset [0;37mcomm.go:36[0m

ERROR
12:37:40
[0;37m12:37:40.679 [31mERROR [0;34m floodsub: [0merror reading rpc from <peer.ID VDtHgR>: connection reset [0;37mcomm.go:36[0m

ERROR
12:36:03
[0;37m12:36:03.684 [31mERROR [0;34m floodsub: [0merror reading rpc from <peer.ID abQa2D>: connection reset [0;37mcomm.go:36[0m
"

**Comment by 42piratas** [comment]
Hey @NSamii 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you still face the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repo and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers!
