### ISSUE TITLE
Conflict between the data provided in Karma and the way an entry acts when I try to publish it

### ISSUE THREAD

**Issue by SaiKarthik1911** [AkashaProject/Alpha#157]
Steps to reproduce:

1) Try to create an which is a 'Link'
2) Enter some website link - www.abc.com
3) Click on Publish

It does not allow me to publish because it says that I must add at least one tag.

4) Add some tag - 'alphabets'
5) Click on Publish

It says that I do not have enough Karma to create tags. But when I click on the 'Karma' circle, it says - "At your current level you can: Publish Entries, Vote, Comment".

Some screenshots:

![screen shot 2018-03-16 at 10 41 54 am](https://user-images.githubusercontent.com/1278046/37536435-ce7cef28-2907-11e8-8ced-4547355a82c8.png)
![screen shot 2018-03-16 at 10 41 31 am](https://user-images.githubusercontent.com/1278046/37536436-ce98df94-2907-11e8-9eb6-3af66b8500c2.png)
![screen shot 2018-03-16 at 10 41 02 am](https://user-images.githubusercontent.com/1278046/37536438-ceb3e226-2907-11e8-90b7-ee1214465a3d.png)

Isn't this a conflict? Either the 'Karma' should say that I can not publish at my current level or I should be allowed to publish without creating a tag (which requires karma). 

If everything is working as expected. Am I missing something here?

**Comment by sebastianrs95** [comment]
Well, the thing is that you can only create tags when you have Karma level 1 or above. You do need to add a tag, but in your current level only those that already exist. Try adding the tag sports.

**Comment by SaiKarthik1911** [comment]
That worked. Thank you! The message - "Sorry! you don't have enough karma to create tags." was not explaining that. I think the message would have been helpful if it said - "Sorry! you don't have enough karma to create tags. Please choose from the existing tags."

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#271
