### ISSUE TITLE
IPFS dead and unrestartable on Mac OS X

### ISSUE THREAD

**Issue by jbrukh** [AkashaProject/Alpha#16]
Unexpectedly, the IPFS connection went dead at some point:

<img width="1298" alt="screen shot 2017-01-06 at 5 48 25 pm" src="https://cloud.githubusercontent.com/assets/44650/21735527/864d2986-d438-11e6-8699-1412620aa0b2.png">

Turning the service back on has no effect:

<img width="1291" alt="screen shot 2017-01-06 at 5 49 31 pm" src="https://cloud.githubusercontent.com/assets/44650/21735529/8b59056c-d438-11e6-9431-b4e69af7aefa.png">

**Comment by arobbins** [comment]
I'm experiencing this as-well. Although my error seems to be subtly different. 

Ethereum connects and syncs fine but seems to timeout during the IPFS connection (first screenshot). When I click the IPFS icon, on the next screen I'm not able to click the IPFS service toggle button in the bottom left. (second screenshot)

macOS version: 10.11.6 (15G1108)

![akasha-1](https://cloud.githubusercontent.com/assets/961947/21752928/21902096-d5a7-11e6-989f-b5d0f798bbfb.png)
![akasha-3](https://cloud.githubusercontent.com/assets/961947/21752927/218b1bfa-d5a7-11e6-85d5-b8b8abf41b5d.png)

**Comment by boblucore** [comment]
I am having the same problem. Searching for IPFS in the activity monitor shows that it is not running, so the advice to stop it there and restart Akasha does not work.

**Comment by jbrukh** [comment]
Still happening in 0.3.0.

**Comment by arobbins** [comment]
Still happening for me as-well. App is unusable on macOS.

**Comment by SeverS** [comment]
Hey @arobbins can you check the logs tab from ipfs modal? Click ipfs icon and navigate to logs tab. Can you post any logs from there? Make sure to remove/hide any personal data like ip or user from  logs. 

Thanks

**Comment by jbrukh** [comment]
I figured out the issue on my end. Port 8080 was being used by another application, namely parity UI daemon in my case. I went through the process of turning the daemon off, and then Akasha operates.
