### ISSUE TITLE
Importing Linux Desktop Account to beta.akasha.world

### ISSUE THREAD

**Issue by kiarga** [AkashaProject/Alpha#162]
If there is a better location for this question please advise and I will move it. There isn't much activity on Reddit or Discord.

I created an Akasha account with the desktop Linux client and am trying to get the same account open via beta.akasha.world.

The idea is to take my keystore backup file from the desktop client, extract a private key from it, then use a BIP39 tool to convert the private key into a seed phrase that I can import into Metamask.

Could somebody point me to a tool that I can use to extract my private key from the keystore backup file?

Thanks, if I can achieve this I'll produce a guide for the community.

Edit: I am trying this: `openssl aes-128-ctr -d -a -in key.txt -out secrets.txt.new`

And getting this: `error reading input file`

The input file is a renamed version of of my unzipped keystore file from Akasha.

**Comment by sebastianrs95** [comment]
hello, kiarga. 

The following guide explains how to import an account from the desktop dapp to the web dapp.

https://akasha.helpscoutdocs.com/article/31-how-to-import-an-account

Also, regarding this kind of questions, please share them in Discord, I'll respond to you there 😁
