### ISSUE TITLE
Error Code ISE01

### ISSUE THREAD

**Issue by Pellease** [AkashaProject/Alpha#166]
So I am trying to check out Akasha and to be honest I'm a complete newb.

As I'm glancing around trying to figure out what everything does it says I have an error in trying to access the IPFS service.

Not sure how to get this working?

<img width="390" alt="screen shot 2018-05-03 at 7 03 35 pm" src="https://user-images.githubusercontent.com/38967219/39610440-2581eda0-4f05-11e8-8452-7e815d96041d.png">
<img width="360" alt="screen shot 2018-05-03 at 7 03 42 pm" src="https://user-images.githubusercontent.com/38967219/39610441-2597d6e2-4f05-11e8-8bdc-90913163d817.png">

**Comment by wschwab** [comment]
I can second this. Firefox (with MetaMask and IPFS Companion) on Windows 10. Trying to turn on IPFS service using the slider in the screenshot above results in another failed attempt with the same error message pictured above.

**Comment by Pellease** [comment]
Chrome here on Mac Os High Sierra.

**Comment by MarkMatz** [comment]
I was having the same problem as well, using Chrome and metamask + IPFS companion on windows 10. Manually switching to embedded from external using the IPFS companion interface fixed the issue for me. (shown in pic) 

![clipboard01](https://user-images.githubusercontent.com/39717648/40635616-e6316f7c-62c8-11e8-9f8a-f4c7abc1f426.jpg)

**Comment by 42piratas** [comment]
Hey @Pellease @wschwab @MarkMatz 

I'm sorry for the late reply, and thank you very much for your feedback! We appreciate your contribution.

I'm closing this issue as it seems to be solved in the latest beta.

Again, thank you very much! 

Cheers!
