### ISSUE TITLE
Rotate profile images 

### ISSUE THREAD

**Issue by lukewilliamboswell** [AkashaProject/Alpha#18]
Nice work so far!

Its probably already on your radar but I uploaded a profile pic and I couldn't get the rotation correct. Perhaps you can add the functionality to rotate uploaded image?

**Comment by MihaiAlisie** [comment]
Hi there!

Thanks for the kind words! We'll look into it, however it's not a priority atm as we still have a lot of work to do in many other areas. In the meantime please rotate the image locally on your computer before uploading :)

Best regards,
Mihai
