### ISSUE TITLE
hitting "enter" while editing and entry scrolls the editor down to the bottom.

### ISSUE THREAD

**Issue by dragosroua** [AkashaProject/Alpha#19]
It's a bug insomuch as it hinders the UI experience. If a post is big, it's significant. Tested on Safari on Mac.

**Comment by SeverS** [comment]
Hello @dragosroua and thank you for reporting this.
This is a known bug from an external library which is not in our control. It will be addressed in the next releases.

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#291
