### ISSUE TITLE
How do I import an account on Mac?

### ISSUE THREAD

**Issue by folsen** [AkashaProject/Alpha#20]
I created an account on Linux, but when I copied the `.ethereum` folder from my home folder to my mac, it did nothing. How do I import my account to so I can use it my mac as well?

**Comment by SeverS** [comment]
Hello @folsen 
You must copy only the key / keys for that account. More info [here](https://github.com/AkashaProject/Alpha/wiki/FAQ#how-can-i-backup-my-identity-andor-port-it-to-another-machine)
If you encounter any troubles please let me know.

**Comment by folsen** [comment]
Ah, that worked well, thank you. I should have checked the FAQ more thoroughly first.
