### ISSUE TITLE
Forward/Backward navigation buttons

### ISSUE THREAD

**Issue by marchbnr** [AkashaProject/Alpha#21]
Great work on the mac client! Everything works smoothly for me at this point.

I would suggest to add navigation buttons to the top left. I guess no explanation is needed. Since other platforms are used with a browser, they all have this feature out of the box.

**Comment by JanKalin** [comment]
A very good addition would also be tabbed browsing - opening tabs for clicked-on entries.

But at the very least, closing an article should bring you back to the previous view of the list from and *not* have the list scrolled to the top!

**Comment by 42piratas** [comment]
Hey @marchbnr and @JanKalin!

First, I'm sorry for the late reply. 

Have you already tried the latest beta version? If you have any feedback, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers! :pray::metal:
