### ISSUE TITLE
Editing/updating feature

### ISSUE THREAD

**Issue by mcgravier** [AkashaProject/Alpha#25]
It often happens, that I'm making silly mistakes/spelling ect, that I want to fix by editing original post. I know, that deletion is impossible, but this could be done trough collapsing original post into small link, and having most recent version visible by default

**Comment by bogdanbrezuica** [comment]
Hello and thanks for testing AKASHA!

As this was in our plans from the beginning (and we also received lots of requests for this feature), we are already working on it!

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#292
