### ISSUE TITLE
Advanced user side content filtering

### ISSUE THREAD

**Issue by mcgravier** [AkashaProject/Alpha#26]
For consideration: Since all content is in public database, advanced user side filtering may be viable. For example, I may consider certain highly upvoted entry to be very low quality. So I might want to make (or use) filter that will decrease visibility that particular entry for me, and all other entries upvoted by the same users.
On the other hand, I might find interesting entry that has almost no upvotes. So I'd like to increase visibility of entries upvoted by these users. All user side, and completly transparent to rest of the network.
Synereo is taking similar approach, and I believe, it may be very intersting feature of decentralized social networks.

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#290
