### ISSUE TITLE
RFFE01 What does it mean?

### ISSUE THREAD

**Issue by finscher** [AkashaProject/Alpha#27]
Using Windows Version of Akasha, V 0.3
Registering identity is not working. 
The account can not be created and i got the error code: 

RFFE01 

Clicking the "Retry step" Button several times makes no change.

**Comment by jonathan-soifer** [comment]
On Mac OSX 10.12.2 (Sierra)
I'm running brew upgrade because Go seems to be outdated, I'll post news if it solves it.

**Comment by SeverS** [comment]
@finscher our faucet is overloaded right now. we are working for a solution. Unfortunately we have no ETA. I will keep this issue updated.
Thanks

**Comment by finscher** [comment]
Thanks!

**Comment by JanKalin** [comment]
Same here.
Trying to create identity I got:
```
Your identity is broadcasted into the AKASHA private network.

This will take a few moments ...
Current Status:Receiving aethers from AKASHA

RFFE01
```
The `UTC--` file is created.
Waited a bit, clicked "Abort" then got an error:
```
DTPE01

Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
```

**Comment by jaysoifer** [comment]
@finscher: i don't think you need to close this as 

@SeverS said:
> I will keep this issue updated.

**Comment by SeverS** [comment]
@finscher btw you can use ctrl+r to force reload the app. This way it will ensure the actual retry the request to faucet.

cmd+r on mac :)

**Comment by jonathan-soifer** [comment]
Not sure it was a good idea telling me that. 

Now I'm Command+R'ing it till death.

**Comment by jonathan-soifer** [comment]
Not sure this is helpful but now I'm getting a:

    RFFE01

    Unauthorized

**Comment by finscher** [comment]
Now I´m getting:
Waiting for faucet transaction to be mined. Transaction id:

It seems to be working!

**Comment by jonathan-soifer** [comment]
Yup! It is mining!

**Comment by SeverS** [comment]
Yes it should work now! 
Thanks guys for waiting.
Enjoy!

**Comment by JanKalin** [comment]
Yes, it works

**Comment by jonathan-soifer** [comment]
Yup. Solved.
