### ISSUE TITLE
Feature - IPFS http api and RPC support

### ISSUE THREAD

**Issue by kumavis** [AkashaProject/Alpha#28]
I would prefer to be able to provide:
* a url for Eth RPC (e.g. `http://localhost:8545`)
* a url for IPFS http api (e.g. `http://localhost:5002`)

Rather than Akasha having direct access to the data directories

**Comment by MihaiAlisie** [comment]
Hello @kumavis!

For the alpha we're using a private network which requires a custom genesis block and network id. The simplest way to get started would be to go with the express setup and let it download the preconfigured geth/IPFS - they create new folders for the chain/keystore and doesn't touch the Ropsten/main network data.

That being said, down the line we will develop things to be as interoperable as possible - it's just a matter of time until things will get better!

Cheers!

**Comment by kumavis** [comment]
Why use a custom testnet? why not use morden?
