### ISSUE TITLE
Chat feature general improvements

### ISSUE THREAD

**Issue by rabbit** [AkashaProject/Alpha#31]
## Description

Outside of the obvious need for creating new chat channels, the ability to self-censor unwanted authors or content, and other such high demand requests; here are my recommendations for improvements to the Chat feature. These are simply suggestions, I don't have enough optics on the design direction of Akasha to say whether or not they fit the intent of the app.

### Passive Inspection of Participant Profiles

Currently if you want to jump to a persons profile from chat (to start following them, for example) you have to jump out of chat. Following several people requires more effort than it's worth.

### Links

It's good to deny the use of links to protect users however there might be a compromise that enables users to have some link functionality. When clicking a link, open a dialog that displays the full link with a button for copying it to the clipboard and a brief explanation about user safety. If we're feeling extra bold, include a checkbox to always copy links making the dialog disappear and the user accepts the responsibility.

### Scroll Lock

Currently the chat window scrolls when new content is added. In some cases this is desirable but the lack of an option makes it difficult to review older history. A simple compromise could be to always have scroll locking enabled with a bottom bar that appears when new content has been added. Gitter, for example, adds an "Unread" box in the lower right corner that you can click to skip back to the bottom.

### Emoji Support

I'm biased 🌟 but I'm a big fan of in-app emoji support. Something similar to the Twitter emoji picker would be an excellent addition for giving reactions and coloring the chat experience. It may be a good idea to limit the number of emoji that can be rendered per line, it wouldn't surprise me if spam containing large blocks of emoji caused more lag than regular text.

### Recent Participants

I'm going to assume it's probably not feasible to have a list of users unless they have participated and even further it's probably not desirable to have a full list of users that have ever participated, however a listing of participants from the previous 24 hours could be useful including the ability to jump back to the last thing they said.

### Whisper-level Chat Interoperability

It would be ideal if other chat programs developed for Ethereum could easily make use of the same chat channels used by Akasha. I'm not sure what all would be involved in making that happen -- at minimum a developer library or similar integration point for relying parties -- but it would reinforce the topic-oriented nature of Akasha. Also on this point, a standalone app for Status that -only- integrates the chat feature would be appealing to me.

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#287
