### ISSUE TITLE
SIE01 Cannot start IPFS service.

### ISSUE THREAD

**Issue by mcgravier** [AkashaProject/Alpha#34]
Windows 7 64bit

logs:
info
13:08:11
ipfs exited with code: 1, signal: null

error
13:08:11
Error: cannot acquire lock: file "C:\\Users\\Adam\\.ipfs\\repo.lock" already locked

info
13:08:11
Initializing daemon...

**Comment by scottc** [comment]
You cannot run two instances of the IPFS daemon (service).

try:

1. Close AKASHA
2. Stop IPFS daemon
3. Check task manager and terminate all instances of IPFS, if it hasn't already stopped.
4. Run AKASHA again

If AKASHA's IPFS instance still refuses to run, you can try delete the `C:\Users\Adam\.ipfs\repo.lock` file, or the entire `C:\Users\Adam\.ipfs\` directory and try again. Take a backup if you care about the contents.

**Comment by kenshyx** [comment]
Don't delete `.ipfs` folder, you can loose your profile avatar and all media linked to your Akasha profile!

**Comment by mcgravier** [comment]
Error appeared after computer restart, I'm sure there was no IPFS daemon working in the backgrund.
I double chcecked, restarted Akasha, and same issue appeared

Only removal of repo.lock file helped. Akasha works fine now

**Comment by chevdor** [comment]
I had the same (or similar issue).
After looking at the logs, I saw that the issue is that the version of ipfs provided by Akasha was too old.
I could fix the issue with (for OSX):
`cp /usr/local/bin/ipfs ~/Library/Application\ Support/AKASHA/`
