### ISSUE TITLE
Bug with removing + adding links in profile

### ISSUE THREAD

**Issue by haywirez** [AkashaProject/Alpha#35]
Small 🐛...when you remove a link in your profile and subsequently add a new one, the keyboard input is bound to the first link box instead & ends up messing that entry up.

**Comment by bogdanbrezuica** [comment]
Thanks for helping out and reporting this bug! It will be fixed in the next release. Until then, keep on enjoying AKASHA!

**Comment by SeverS** [comment]
solved in 0.4.0.
thanks @haywirez for reporting this.
