### ISSUE TITLE
SIE01 connect ECONNREFUSED 127.0.0.1:5001

### ISSUE THREAD

**Issue by lanzafame** [AkashaProject/Alpha#41]
OS: macOS 10.12.3 Beta (16D30a)
Akasha: Version 0.3.0 (0.3.0)

Setup and initial session of Akasha, everything appeared to work well. Second session, started up fine but couldn't access the profile tab. The third session wouldn't sync IPFS and printed this: 
```
SIE01connect ECONNREFUSED 127.0.0.1:5001
```

Not sure what other information could be useful, but if there is anything I am happy to help 👍

**Comment by lanzafame** [comment]
Following the suggestion in #34, I killed the IPFS daemon and started Akasha again. It seems that Akasha is able to connect to IPFS now but sync is taking _quite_ a while so I will leave this open until I have been able to successfully login.

**Comment by SeverS** [comment]
Hi @lazanfame, 

Did you successfully logged in?

**Comment by lanzafame** [comment]
Woops, yes I did. I shall close this. 👍
