### ISSUE TITLE
Cannot get passed 'Registering Identity' Screen

### ISSUE THREAD

**Issue by fiiingers** [AkashaProject/Alpha#42]
I can't get passed the 'registering identity' screen.  It gives me the following error... 

RFFE01 connect

ENETUNREACH 138.68.78.152:1337

**Comment by SeverS** [comment]
Hi @fiiingers,  sometimes our faucet gets overloaded and cannot serve your request. Please try again in few minutes.

Thanks

**Comment by SeverS** [comment]
Hello @fiiingers, 
Did you managed to pass that error? If you have any troubles please let us know :) 
Thanks

**Comment by fiiingers** [comment]
I kept trying throughout the day, and eventually got in once.  I set up a profile, but then couldn't get back in again for a couple of days.  I've tried again just now and it seems to be working fine.  Looking good!

**Comment by SeverS** [comment]
Hi @fiiingers,
Can this issue be closed? Must make room for the new ones 😄 .
Thanks!

**Comment by fiiingers** [comment]
Sure.  I just updated to 0.4.0 and everything still seems to be working fine.  I no longer get this error.

Many thanks
