### ISSUE TITLE
Error: Tags should have at least 4 characters.

### ISSUE THREAD

**Issue by smoove** [AkashaProject/Alpha#43]
I think there should not be a minimum length for tags. There are a lot of words / abbreviations that have less than 4 characters:
eth, php, web, css, js, seo, tax, zoo etc.

**Comment by davidak** [comment]
FSF, UX, C, ...

**Comment by MihaiAlisie** [comment]
Many thanks for testing AKASHA!

Feedback noted. This is a breaking change as it requires changes at smart contracts level and will be implemented probably after version 0.6.

**Comment by davidak** [comment]
@MihaiAlisie can you leave the issue open until it is implemented?

This way people can see that it is planned and don't create new issues for it.

**Comment by MihaiAlisie** [comment]
Sure, sounds like a good idea! :octocat:

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#297
