### ISSUE TITLE
Reduce clicks for Login view

### ISSUE THREAD

**Issue by rabbit** [AkashaProject/Alpha#44]
## Description

It is common that I want to remember my passphrase for longer than 5 minutes when I login. This requires a click on duration and a click to checkbox for remembering passphrase.

## Recommendation

After the user clicks to display the duration dropdown ...

* if the user clicks on a dropdown value, automatically check to remember passphrase.
* if the user clicks outside of the dropdown to dismiss it, do nothing.

**Comment by SeverS** [comment]
Added in 0.4.0 :).
thanks for suggestions :D
