### ISSUE TITLE
Phrasing on illegal characters error text for tags is inaccurate

### ISSUE THREAD

**Issue by rabbit** [AkashaProject/Alpha#45]
## Description

Illegal characters for tags produces the following error message:

```
Tags can contain only letters, numbers, one dash ( - ) or one underscore ( _ ).
```

This isn't entirely accurate since tags must also begin and end with a letter or number.

* 👍 `foo-bar`
* 👍 `foo_bar`
* 🙅 `-foobar`
* 🙅 `foobar_`

## Recommendation

* `Tags can contain only letters, numbers, and one dash ( - ) or underscore ( _ ) between characters.`
* `Tags can contain only letters and numbers. One dash ( - ) or underscore ( _ ) may separate words.`

**Comment by SeverS** [comment]
Solved in 0.4.0.
thanks @rabbit
