### ISSUE TITLE
Unable to access Session and Entries views after a period of time.

### ISSUE THREAD

**Issue by rabbit** [AkashaProject/Alpha#46]
## Description

Since `0.3.0` I have been consistently unable to access the Session and Entries views after a period of time. When viewing posts there is a style change visibly toggled but no sidebar overlay appears. The issue is likely in the sidebar overlay since Stream, People, and Chat views are still accessible.

If I have time I'll start akasha with a debug console to see if any errors pop up. For now, I wanted to make sure this was tracked.

**Comment by SeverS** [comment]
Hello @rabbit.
We are aware of this since everyone is affected.
We are working on a fix and will be shipped with the next release.

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#283
