### ISSUE TITLE
Login greyed out

### ISSUE THREAD

**Issue by rherronify** [AkashaProject/Alpha#47]
Ive installed Akasha and created an identity but then had to format and rebuild my laptop.
Then I reonstalled Akasha but the ption to 'Login' is greyed out.
How do I login with my saved Akasha login details?

**Comment by SeverS** [comment]
did you backed-up you key? If you formatted you hdd the key is gone so unless you didn\`t saved it somewhere you can\`t login (actually you can`t even see your previous identity).
Is suggest to create a new identity and backup you key using this wiki https://github.com/AkashaProject/Alpha/wiki/FAQ#how-can-i-backup-my-identity-andor-port-it-to-another-machine
Cheers

**Comment by rherronify** [comment]
Thanks for your help Sever,
yes I backed up my key, I wrote it out on a piece of paper when I first set
up Akasha.
Do i just create a text file with the key and save it in C:/Users/%Your
username%/AppData/Roaming/Ethereum/akasha-alpha/keystore  ?
Is there a particular format for the file?
Regards
Ronan



Ronan Herron
[image: https://]about.me/ronanherron
<https://about.me/ronanherron?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by SeverS** [comment]
hi @rherronify,
please note that the key is not your passphrase or ethereum address so i could not imagine how could you wrote it on paper. 
I recommend you to create a new AKASHA profile.
Cheers

**Comment by rherronify** [comment]
Its 46 character long Sever.
I saved it to a text file called Keystore and saved it in C:/Users/%Your
username%/AppData/Roaming/Ethereum/akasha-alpha/keystore
Then I retried logging in but its not working

The problem with setting up a new profile is it tells me a profile already
exists for that email address.
Could you please delete the profile associated with ronanherr@gmail.com ?

Rgds
Ronan


Ronan Herron
[image: https://]about.me/ronanherron
<https://about.me/ronanherron?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by SeverS** [comment]
Hi @rherronify.
That is your Ethereum address. It has 42 chars and starts with 0x....
You need a key (file) to access that address. 
If you try to make a new profile you can find the generated key in `C:/Users/%Your
username%/AppData/Roaming/Ethereum/akasha-alpha/keystore`. 
We can't delete any profile. 
Cheers
