### ISSUE TITLE
issue when connecting with windows 7

### ISSUE THREAD

**Issue by inasacu** [AkashaProject/Alpha#48]
issue when connecting with windows 7

info
13:50:50
ipfs exited with code: 1, signal: null

error
13:50:50
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

info
13:50:50
Swarm listening on /ip4/127.0.0.1/tcp/4001 Swarm listening on /ip4/169.254.211.196/tcp/4001 Swarm listening on /ip4/169.254.42.186/tcp/4001 Swarm listening on /ip4/169.254.67.64/tcp/4001 Swarm listening on /ip4/192.168.1.43/tcp/4001 Swarm listening on /ip6/::1/tcp/4001

info
13:50:49
Initializing daemon...

info
13:50:04
ipfs exited with code: 1, signal: null

error
13:50:04
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

error
13:50:04
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

info
13:50:04
Swarm listening on /ip4/127.0.0.1/tcp/4001 Swarm listening on /ip4/169.254.211.196/tcp/4001 Swarm listening on /ip4/169.254.42.186/tcp/4001 Swarm listening on /ip4/169.254.67.64/tcp/4001 Swarm listening on /ip4/192.168.1.43/tcp/4001 Swarm listening on /ip6/::1/tcp/4001

info
13:50:02
Initializing daemon...

**Comment by SeverS** [comment]
Hi @inasacu 
looks like your 5001 port is used by other service
you can change that port by editing `C:/Users/%Your Username%/.ipfs/config` file.
this line `"API": "/ip4/127.0.0.1/tcp/5001"` should be changed to `"API": "/ip4/127.0.0.1/tcp/5002"` or some other port which is not used.
If you have any troubles please write back.
Thanks
