### ISSUE TITLE
Cannot post if first line in body is an link

### ISSUE THREAD

**Issue by 0xb100d** [AkashaProject/Alpha#50]
I only tested this once, but I could not publish a post when the first line of the body was either a link or a blank line (break). Only did it once so not sure which one was causing the problem. When I changed the first line to a period (.) it allowed me to publish it.

**Comment by SeverS** [comment]
Hello 0xb100d,
I tried to reproduce this and i was able to publish an entry starting with a link. There is no validation for the entry's body right now and i was curious if you encountered any errors. 

Thanks

**Comment by haywirez** [comment]
Seems like you cannot publish/save a draft if there are any links at all in the post body.
