### ISSUE TITLE
Problem With IPFS

### ISSUE THREAD

**Issue by q112358** [AkashaProject/Alpha#53]
Hi

When I attempt to login to Akasha, I get the following:

> Synchronization completed
> 
> Synchronization is complete. IPFS service needs to be started in order to continue. You can start it manually from the status bar in the header or click NEXT to start it automatically.
> 
> SIE01Cannot start IPFS service. Check logs for more details

Investigating the IPFS icon in the header, I turned IPFS on under Settings, but in the corresponding logs I get:

> Error: cannot acquire lock: file "C:\\Users\\trans\\.ipfs\\repo.lock" already locked

Any suggestions?

@transhuman

**Comment by SeverS** [comment]
Hi @transhuman,
You can delete that file (ONLY repo.lock file) and restart AKASHA. 

Cheers
