### ISSUE TITLE
Follow button does not toggle in mouseover popup when following from profile

### ISSUE THREAD

**Issue by ghost** [AkashaProject/Alpha#54]
Clicked "Follow" on @MihaiAlisie's profile (mihai on Akasha), then clicked into a post. Moused over his avatar and saw a "Follow" button in the popup (as opposed to "Unfollow"). Profile button had switched to "Unfollow" already. Browsed around a little to give the transaction time to get mined, just in case. Returned to the post again, observed the same behavior.

**Comment by bogdanbrezuica** [comment]
Hello! Thanks for finding this issue. We will fix it for the next release, so stay tuned! Cheers!

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#281
