### ISSUE TITLE
Cannot Start IPFS Service

### ISSUE THREAD

**Issue by JakeVartanian** [AkashaProject/Alpha#58]
Error: serveHTTPGateway: manet.Listen(/ip4/127.0.0.1/tcp/8080) failed: listen tcp4 127.0.0.1:8080: bind: address already in use

I keep getting this error. The Eth chain portion syncs fine, but not IPFS component.

**Comment by ahowl7mx** [comment]
Woot!  Got this one to work.  Had the same problem.  Your 8080 port is in use by another program, probably JAVA.

1)  Open command window as administrator (right click window icon)
2)  Type: netstat -ao
3)  Look for the PID number that is using port 8080.  Write it down.
4)  Go to task manager (ctrl + alt + del)
5) Go to the "Details" tab and sort by PID
6) Find the process using your PID and kill it.
7) Now try running IPFS

Art

**Comment by emptyflash** [comment]
Any chance we can change this number? Either through config or updating the akasha app itself? 8080 is a really common developer port and it'd be nice to be able to have akasha open will working on other stuff.

*EDIT*: Found this in `~/.ipfs/config`:
``` json
{
  "API": {
    "HTTPHeaders": null
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ]
  },
...
```
So you can change that 8080 to be some other number that doesn't conflict.

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#293
