### ISSUE TITLE
SIE01Cannot start IPFS service

### ISSUE THREAD

**Issue by duxization** [AkashaProject/Alpha#60]
I am getting this error:

Error: serveHTTPGateway: manet.Listen(/ip4/127.0.0.1/tcp/8080) failed: listen tcp4 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

Pls help.

**Comment by ahowl7mx** [comment]
I have the same error.  On Windows.  Geth synchs and is ready, IPFS brings up a window really quickly and then it disappears.

**Comment by CodySork** [comment]
Getting the same error on Linux.

**Comment by egall** [comment]
Hi, first off I wanted to say really cool project!

I'm running Akasha 0.5.0 from MacOS 10.9.5 with ipfs version 0.4.5 and geth version 1.5.9

I'm seeing "SIE01Cannot start IPFS service. Check logs for more details." being displayed in the UI.

Looking at the ipfs settings-log I'm seeing a number of the following error (all the same):
"Error: Your programs version (4) is lower than your repos (5). Please update ipfs to a version that supports the existing repo, or run a migration in reverse. See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details."

When I tried running fs-repo-migrations I get "ipfs migration: already at or above target version number".

The last message in the ipfs log says "Initializing daemon..." however I don't see any ipfs procs running on my system. 

sidenote: I've run "ipfs daemon" and "ipfs swarm peers" successfully via CLI and can read and write to the fs so I think I'm okay there? (Made sure to stop the ipfs daemon before running akasha tho)

I'd love to help out more but I'm stumped on this one. If there's any other info that could help please let me know.

Also, is this the appropriate method for filing bugs? Is there a template y'all would like to see for filing bugs?

**Comment by forkerino** [comment]
I give up. Can't get it to synchronize. See you when there is a beta.

**Comment by SeverS** [comment]
@forkerino please check if those 2 icons from the top of the sinchronization panel have red or green borders. if they are red you can check the logs by clicking them.

Thanks

**Comment by forkerino** [comment]
@SeverS 
14:17:20
geth: exited with code: 1

I0316 14:17:19.968300 node/config.go:445] Failed to start Ledger hub, disabling: libusb: not found [code -5]

**Comment by SeverS** [comment]
@forkerino do you have a ledger wallet or some 2 factor auth device attached to your computer?

**Comment by forkerino** [comment]
@SeverS nope!

**Comment by SeverS** [comment]
@forkerino if you have time, i would be happy to assist you in this issue on our Slack channel http://akashaproject.slack.com or if you create a new issue.

Thanks

**Comment by pdxwebdev** [comment]
2 cents: I also received the "SIE01Cannot start IPFS service. Check logs for more details." error but because I already had a webserver running on port 8080.

**Comment by teferra** [comment]
geth starts and synchs all-right but IPFS exited with code: 2, signal: null. Tried to start manually from setting but throw a lot of panic errors.  

 But the surprise was "Swarm listening on /ip4/127.0.0.1/tcp/4001 Swarm listening on /ip4/192.168.43.71/tcp/4001 Swarm listening on /ip4/x.x.x.x/tcp/4001 Swarm listening on /ip6/::1/tcp/4001 API server listening on /ip4/127.0.0.1/tcp/5001" 

Is Akasha using IPFS or swarm?

**Comment by chevdor** [comment]
It is using IPFS.
I had the same (or similar issue).
After looking at the logs, I saw that the issue is that the version of ipfs provided by Akasha was too old.
I could fix the issue with (for OSX):
`cp /usr/local/bin/ipfs ~/Library/Application\ Support/AKASHA/`
