### ISSUE TITLE
Selecting IPFS directory not possible on OS X

### ISSUE THREAD

**Issue by davidak** [AkashaProject/Alpha#62]
I have IPFS already installed, so i tried to select it's directory, which is the default `~/.ipfs`.

Finder don't lists hidden directorys and i wasn't able to drag and drop it or type the path in.

https://youtu.be/S6gYJ1-s2Yk

---

AKASHA Version 0.4.0
OS X 10.10.5

**Comment by davidak** [comment]
Workaround: Display hidden directories in Finder and drag and drop it onto the file selection dialog.

The program should test if the default location is available and use it.

**Comment by bmann** [comment]
I had IPFS installed but wanted to have a fresh install. Creating a new directory not starting with a "." and selecting it worked fine.

I agree, it should detect an existing .ipfs directory in the default location of "~/.ipfs" and just work.

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#294
