### ISSUE TITLE
SIE01Cannot start IPFS service. cannot acquire lock - already locked

### ISSUE THREAD

**Issue by IchNameleTonP** [AkashaProject/Alpha#64]
Error: cannot acquire lock: file "C:\\Users\\*\\.ipfs\\repo.lock" already locked

Despite this hiccup AKASHA looks promising :)

Edit: Windows

**Comment by bogdanbrezuica** [comment]
Hello. Try to delete (only) that file and restart the application.

**Comment by IchNameleTonP** [comment]
@bogdanbrezuica Many thanks, Akasha resolved itself :) - ticket closed!
