### ISSUE TITLE
Stuck on 'There are no peers online right now' Linux

### ISSUE THREAD

**Issue by alphanmoon** [AkashaProject/Alpha#66]
Synced, Loged in but permanently stuck on 'There are no peers online right now' in stream field. Is it ok?
![21298598347](https://cloud.githubusercontent.com/assets/25549734/22703577/ad61c1b6-ed75-11e6-8ed2-9691a10392c0.jpg)

**Comment by Julian-Dumitrascu** [comment]
I see this message often. I suppose I have no access at those moments to the disk on which these data are written. I would like to find out the rules according to which the data are stored. It seems that the posts and comments I create are stored on my computer, and that I may not change this rule. Where are the data stored that make up the application framework? Where are the common data stored, e.g. upvotes?

**Comment by MihaiAlisie** [comment]
@alphanmoon The message `There are no peers online right now` usually means that the people who published things went offline before the content could propagate into the p2p network. You could also try a `Ctrl/Cmd+R` to make sure that it doesn't have to do with your local settings.

@dearjulian please find bellow my answers:

> Where are the data stored that make up the application framework?

Locally, the entire dapp is designed to work client-side.

> It seems that the posts and comments I create are stored on my computer,

When you "publish" something you are broadcasting into the Ethereum network an IPFS hash where people can find what you published - in our case your followers will be notified that you published "X". There are no servers so the content propagates through the p2p network as people read, upvote or bookmark your entry.

> , and that I may not change this rule.

How do you want change it, considering that there are no servers where your content could be served from?

> Where are the common data stored, e.g. upvotes? 

The upvotes are stored in smart contracts, currently running on a private Ethereum network.

**Comment by alphanmoon** [comment]
@MihaiAlisie Seems it's an IPFS issue after installing IPFS at first but using express option in AKASHA but not sure. I killed daemon and removed IPFS from /bin and completely reinstalled AKASHA but with no result. Looks something goes wrong with API/Gate, next step is to play with daemon options. In fact  everything goes fine on my another Linux machine with no preinstalled IPFS and AKASHA rolling out from the box. Thx for assistance!

**Comment by philipbeadle** [comment]
@MihaiAlisie I'm having the same issue.  I installed Express and have never used IPFS or Ethereum before.  I created an account and then had a look at the Akasha tag and all the entries say "No peers online".    What I don't get is "The message There are no peers online right now usually means that the people who published things went offline before the content could propagate into the p2p network", how did the entry get into my stream if its not propagated?  
I'd suggest not showing these items until its properly propagated, doesn't look good for your awesome project.

**Comment by philipbeadle** [comment]
Ok, seems if you leave it for a bit, 15 minutes in my case, it all starts to work nicely 👍

**Comment by philipbeadle** [comment]
Found another way to get this message, I read a post, went to the person's profile and then tried to read another post and got the peers message instead of the post.  I'd really like to help out and fix a few of these issues but have to wait for the CODE :)  Having fun with this concept though.
