### ISSUE TITLE
Backup button is disabled

### ISSUE THREAD

**Issue by winzig** [AkashaProject/Alpha#67]
I setup Akasha for the first time, on macOS Sierra. After registering my identity, the tips indicate I should "Backup your ID" (it's not clear to me whether they mean the Ethereum Address shown up above, or something else). The "Backup" button near the bottom is disabled, so it's not clear how to proceed. It's also not clear to me how important it is to know/retain the Ethereum Address that is being shown in the window.

<img width="532" alt="screen shot 2017-02-07 at 1 07 27 pm" src="https://cloud.githubusercontent.com/assets/127062/22711629/b8b0e054-ed36-11e6-968a-b88861e05543.png">

**Comment by SeverS** [comment]
Hi @winzig and welcome to AKASHA!
Please follow this wiki [https://github.com/AkashaProject/Alpha/wiki/FAQ#how-can-i-backup-my-identity-andor-port-it-to-another-machine](https://github.com/AkashaProject/Alpha/wiki/FAQ#how-can-i-backup-my-identity-andor-port-it-to-another-machine) . The key starts with `UTC--....`
Copy it to a safe location :).
Cheers

**Comment by winzig** [comment]
Thank you, I'll check it out. FYI there's a typo in the wiki. This:

`On Mac ~/Users/%Your Username%/Library/Ethereum/akasha-alpha/keystore`

Should be:

`On Mac ~/Library/Ethereum/akasha-alpha/keystore`

**Comment by MihaiAlisie** [comment]
@winzig thank you for reaching out!

I just checked the route to keystore on Mac and it is not a typo - the correct one is `~/Users/%Your Username%/Library/Ethereum/akasha-alpha/keystore`. 

The backup button will work in the next release so all this process should become a bit easier.
