### ISSUE TITLE
Update Button Greyed Out (Profile)

### ISSUE THREAD

**Issue by ghost** [AkashaProject/Alpha#69]
I'm unable to save any profile data.

**Comment by bogdanbrezuica** [comment]
Hello. Can you give more details please?
- was the button greyed out from the start or it became so after you clicked it?
- did you try to reload the page?
- any extra info would be great.
Thanks!

**Comment by ghost** [comment]
I should have added more info: Greyed out from the start.. Didn't reload the page. Using Windows version. Updating profile on Linux version *seemed* to go OK, but when I logged back in, all data, including my avatar, had disappeared. Have now managed to re-upload my avatar on Windows machine. Sorry if this is all confusing.

Cheers!

**Comment by bogdanbrezuica** [comment]
Please let me know if this was a "one time only" issue or it happens again. Either way, I will take a look and try to reproduce the issue.

Thanks again for your help!

**Comment by ghost** [comment]
Probably a one-time issues. I'll keep you posted.

Thanks.
