### ISSUE TITLE
Windows Alpha Cannot start IPFS

### ISSUE THREAD

**Issue by ghost** [AkashaProject/Alpha#7]
[ipfs.error_akasha.txt](https://github.com/AkashaProject/Alpha/files/670996/ipfs.error_akasha.txt)
[ipfs.info_akasha.txt](https://github.com/AkashaProject/Alpha/files/670997/ipfs.info_akasha.txt)

**Comment by MihaiAlisie** [comment]
Hello @haelen and thank you for opening this issue!

Have you tried the steps described in this FAQ? https://github.com/AkashaProject/Alpha/wiki/FAQ#i-cant-get-over-the-ipfs-service-in-the-welcome-screen-akasha-synchronises-with-ethereum-but-ipfs-cant-start-so-im-blocked

Hope this helps!

✨ Merry Christmas ✨

**Comment by SeverS** [comment]
@haelen also make sure that the 8080 port is not used.

**Comment by ghost** [comment]
Looks the the problem may have been to do with Firewall permission. I can connect OK now.

Thanks!

**Comment by bitcloudTheFirst** [comment]
same problem here. I had to go to:
C:\Users\[Username]\AppData\Roaming\AKASHA

and run:
ipfs daemon

to migrate IPFS before it would get past the "Synchronisation complete" page. You might need a warning page.. or add "starting IPFS" to your list of things to "next".

**Comment by SeverS** [comment]
Hi @haelen, 
Everything ok now?
