### ISSUE TITLE
Importing an identity file not created by AKASHA is unsuccessful

### ISSUE THREAD

**Issue by zigguratt** [AkashaProject/Alpha#71]
I successfully imported an identity file created by AKASHA on another machine of mine into AKASHA on my MB Pro. Since I already had an existing key file I thought I would try to import that instead. I removed the AKASHA-created file and brought the existing key into the same directory (`~/Library/Ethereum/akasha-alpha/keystore`). AKASHA wasn't running at that time.

When I started AKASHA I got the "create or import" message. I thought it might have been a permissions problem so I set my file to `0600` (from `0644`), but it still wasn't recognized. I put the AKASHA-created file back and removed the other key and when AKASHA started it successfully recognized the key.

**Comment by SeverS** [comment]
Hello @zigguratt,
Importing a key not created by AKASHA will not work since we are using a private blockchain.

**Comment by zigguratt** [comment]
Ah, I didn't know that! Thanks.
