### ISSUE TITLE
Downloading .EXE triggers virus warning

### ISSUE THREAD

**Issue by csharpner** [AkashaProject/Alpha#73]
Downloading AKASHA-win-x64-0.4.0.exe triggered Avast to show a virus warning.

Infection:  Win32:Evo-gen [Sus]

**Comment by SeverS** [comment]
Hey @csharpner,
It is a false positive. You can check it on https://www.virustotal.com/en/
Cheers,

**Comment by montsamu** [comment]
I have the same issue with the 0.5.0 EXE -- I did not have an issue with using the ZIP download, so I would recommend using the ZIP download as an alternative.
