### ISSUE TITLE
IPFS 0.5.0

### ISSUE THREAD

**Issue by dirtyhera** [AkashaProject/Alpha#74]
Hello, was never able to start IPFS on version 0.4.0
Am now trying with 0.5.0 and experiencing the same issue.
I read in one of the tickets that it might be an issue with Parity running in the background? However stopping Parity did not fix error.

error
09:28:45
Error: serveHTTPGateway: manet.Listen(/ip4/127.0.0.1/tcp/8080) failed: listen tcp4 127.0.0.1:8080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by kenshyx** [comment]
close Akasha -> stop parity -> start akasha. When ips circle turns green you can change port 8080 to something else like 8084

**Comment by dirtyhera** [comment]
Perfect, problem solved.
Thanks so much!
