### ISSUE TITLE
Akasha 0.5 error: Your programs version (4) is lower than your repos (5) 

### ISSUE THREAD

**Issue by ontofractal** [AkashaProject/Alpha#75]
I've been trying out the latest version of Akasha and keep getting this error:
```
Error: Your programs version (4) is lower than your repos (5). Please update ipfs to a version that supports the existing repo, or run a migration in reverse. See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details.
```

My ipfs version is 0.4.5 and it seems to be incompatible with Akasha. I've looked into ipfs "reverse migrations" but they are currently unsupported. Relevant: https://github.com/ipfs/fs-repo-migrations/issues/54

Any advice? Thanks.

**Comment by kenshyx** [comment]
Change ipfs storage path from ipfs settings.

**Comment by egall** [comment]
I'm having this issue as well. 

I'm unclear on what I should change the storage path to? Currently my datastore path is ~/.ipfs/datastore (I'm on MacOS 10.9.5).

**Comment by kenshyx** [comment]
From AKASHA settings if you click on ipfs logo(cube) there is an option called `IPFS storage path`. Change it to a new empty folder.

**Comment by egall** [comment]
Awesome, that worked. Thanks!
