### ISSUE TITLE
Interface hard-sized too big for screen

### ISSUE THREAD

**Issue by rowanthorpe** [AkashaProject/Alpha#79]
Since I started using Akasha (on Linux) several releases ago until now (0.5.0) the interface has been hard-sized too big for my screen (I tried to resize the window by dragging the edges, but it doesn't let me), meaning I have to do lots of alt-click-and-dragging the window around to get access to buttons, icons and warnings which are often off the edge of the screen. Even when I do extreme zooming, it only zooms the internal content, but keeps menus and icons along the edge of the window, meaning the problem remains. What is particularly surprising is that I have a HiRes 3200x1800 screen, so expected the window to be dwarfed inside the screen if anything. I waited because I expected it was just a glitch which would be resolved within a version-bump or two, but am reporting it because it is still here.

![akasha-screenshot-20170223](https://cloud.githubusercontent.com/assets/604508/23272300/5e08d132-fa03-11e6-915c-e8fd539dd5c4.png)

**Comment by pradavc** [comment]
Same problem here with Akasha version 0.5.2, and Elementary OS Freya 0.3.2 based on Ubuntu 14.04.

**Comment by rowanthorpe** [comment]
*Update*: The problem I reported happened for me on my custom desktop-environment (which is a mash-up of components from `LXDE`, some obscure projects, and personal script-glue), and if memory serves correctly Akasha had the same problem on `MATE` (`Gnome 2` fork), and also on a few free-standing window-managers I had installed (I think it included `awesome`, `stumpwm`, and perhaps one or two others). When I tried Akasha on `Cinnamon` though this problem didn't exist (I'm guessing `Gnome 3` is therefore the same). This leads me to believe that perhaps something in Akasha is presuming existence of some GTK3-based window-manager functionality (with possible fallback to something QT-specific, I haven't tested any QT-based environment) instead of generic `EWHM`/`ICCCM` methods and `xlib`/`xcb` calls. If it turns out this is the case, and there isn't the desire to make that behaviour more portable, then there should at least be checking-code added to popup a meaningful warning to the user about window-size issues when not running certain window-managers.

**Comment by 42piratas** [comment]
Hey @rowanthorpe and @entropicture!

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
