### ISSUE TITLE
Human Connection

### ISSUE THREAD

**Issue by Kuurusch** [AkashaProject/Alpha#80]
Hey Akasha Team, 
Do you know of the project Human Connection, innitiated from the manager of EUROTRAMP Dennis Hack (https://www.eurotramp.com/ch-de//)? Would be interessting to implement some ideas from there in akasha. He want to build a platform as a open alternative to facebook with some fresh new ideas.
A cooperation between the akasha team and Human Connection could be very fructifying ;)
I think we should anyway work much more in cooperation. Hes project needs a technology like IPFS and ETHEREUM and maybe you could make a symbiosis!

Here is the Link to the Project page: https://de.humanconnection.org/
And here a link to an interview with Dennis Hack: https://kenfm.de/dennis-hack/

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#295
