### ISSUE TITLE
Interesting bug

### ISSUE THREAD

**Issue by voklover** [AkashaProject/Alpha#81]
Hi,
very interesting bug.
1. Yesterday at 17-52 (Moscow) I posted a comment to the post Title by (AKASHA)@Yuki San.
It's there now - all right.
2. In 18-01 I suddenly saw this my comment under the post by 
another author - (AKASHA)@wax miguel 
![18-01m](https://cloud.githubusercontent.com/assets/26093705/23443890/e1332920-fe42-11e6-94b5-8904e23380cc.jpg)
3. At 18-03 I decided to check - perhaps I made a mistake and posted the comment not where needed. It was found I was not mistaken - and there was a comment also.
![18-03m](https://cloud.githubusercontent.com/assets/26093705/23445107/14ba8c14-fe4a-11e6-9e40-26ce1d38a110.jpg)
4. Then, in 18-04, I went back to the text by (AKASHA)@wax miguel - and voila - a comment disappeared.
![18-04m](https://cloud.githubusercontent.com/assets/26093705/23445147/4fb34112-fe4a-11e6-9903-28fccba07a1a.jpg)

Yesterday I decided not to write to you, but the screenshots made.
But bug was repeated today.
See
![2017-03-01_05-40-07](https://cloud.githubusercontent.com/assets/26093705/23445196/c734aeba-fe4a-11e6-91f1-781ac87b5abd.jpg)
![2017-03-01_05-38-16](https://cloud.githubusercontent.com/assets/26093705/23445201/d13ea366-fe4a-11e6-9d5d-4008851f5e75.jpg)
....?

**Comment by SeverS** [comment]
this issue have been addressed in 0.5.1. I think it can be closed now.

Thanks
