### ISSUE TITLE
No explanation about what is gas

### ISSUE THREAD

**Issue by come-maiz** [AkashaProject/Alpha#84]
The first time I encountered the gas concept was when I tired to make a new post.
The tooltip says that is the gas to use in the transaction, but nowhere I got an explanation about what's gas. I have no idea how much is recommended, or what will happen if I use too much or too few. There is also no indication of how much gas is there available, will I run out of gas? All of this questions make it scary to make a first post.

![ekrankopio de 2017-03-07 13-21-44](https://cloud.githubusercontent.com/assets/617831/23673850/68261456-0339-11e7-985a-5c140f40306d.png)

**Comment by webster** [comment]
I agree, an explanation would be helpful. It's unclear when I have ~4.9 AETH how I could use millions of 'gas'. Also, it would be useful to know after publishing how much 'gas' I actually used and why (what factors influenced having to use more vs. less 'gas'). Thanks!

**Comment by therealklanni** [comment]
And we still have no idea what gas is...

**Comment by ervin-lemark** [comment]
The gas should be hidden by default and auto calculated. It should be visible only after the successful post as one of the attributes, preferably as a popup.

The concept of gas is one of the major show breakers with ethereum transactions, in my opinion.

Thanks for your attention and keep up the good work!

**Comment by rychardemanne** [comment]
agreed, needs an answer.

**Comment by ravibhojwani** [comment]
The answer is 42. Lol 😝

**Comment by ravibhojwani** [comment]
There's gas calculators that you could look at depending on your specific issue. Including the calc code in anything Aeternity related would only be temporary, imho

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#298
