### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by xznhj8129** [AkashaProject/Alpha#88]
Entries not publishing
Upvotes not upvoting
Comments not opening
Cant follow people
Latest people loads nothing
Basically all i can do is look at the stream
On windows.

**Comment by SeverS** [comment]
Hello @herrlolzor,

Can you check the logs in `C:/Users/%Username%/AppData/Roaming/AKASHA/logs` folder for any errors?
Also can you specify what version on AKASHA are you running from `help -> version` menu?

Thanks

**Comment by xznhj8129** [comment]
Hello! After retrying this morning everything started working.  It is version 0.5.2
Error logs: http://pastebin.com/x5qTDd8m
