### ISSUE TITLE
ipfs service won't stay on

### ISSUE THREAD

**Issue by somanyquestions** [AkashaProject/Alpha#89]
Having a difficult time syncing due to ipfs service won't start, even when manually switched to "on" it seems it won't stay on. Have been successfully logged in previously and created a profile, but sync not functional today.

**Comment by SeverS** [comment]
hey @somanyquestions, can you chack the logs please? in the same panel where you switch on/off there is a `logs` tab. Anything there?
Also can you specify what version of AKASHA you are running from 'Help -> version' menu
Thanks

**Comment by somanyquestions** [comment]
Hi! Thanks for the quick reply. Version 0.5.2 (windows)Here's a screenshot of my error logs.:)                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: March 16, 2017 10:02 AMTo: Alpha@noreply.github.comReply-to: reply@reply.github.comCc: intunecommunications@gmail.com; mention@noreply.github.comSubject: Re: [AkashaProject/Alpha] ipfs service won't stay on (#89)  hey @somanyquestions, can you chack the logs please? in the same panel where you switch on/off there is a logs tab. Anything there?
Also can you specify what version of AKASHA you are running from 'Help -> version' menu
Thanks

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by SeverS** [comment]
@somanyquestions i can`t see any screenshot...
