### ISSUE TITLE
User profile link behavior is non-intuitive

### ISSUE THREAD

**Issue by rabbit** [AkashaProject/Alpha#9]
## Summary

It's not obvious to the user that clicking the double-square icon next to user profile links will copy the URL to the clipboard.

## Recommendation

Add a UI toast saying "Link copied to clipboard" or similar to indicate to the user no link redirection will occur.

**Comment by MihaiAlisie** [comment]
Hi there! 

First of all, thank you for testing AKASHA and opening all these issues. They help!

This is going to be fixed in the ✨ 0.3.0 ✨ release scheduled for next week ^_^

**Comment by SeverS** [comment]
@rabbit a toast was added in 0.3.0. Thanks for suggestion!
This issue can be closed now.
