### ISSUE TITLE
Linux: Last name not mandatory while registration, but while update.

### ISSUE THREAD

**Issue by Bevor** [AkashaProject/Alpha#90]
I didn't have a IFS oder Etherium account yet, so I created one while registration. The last name was not mandatory. While I was updating my profile, it suddenly was mandatory there.

**Comment by bogdanbrezuica** [comment]
Thanks for reporting this issue! It will be fixed in the next release.

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#282
