### ISSUE TITLE
ipfs issue

### ISSUE THREAD

**Issue by 7sea** [AkashaProject/Alpha#92]
ipfs version is old, if already install new one got error.
and no response for update repo.

**Comment by kenshyx** [comment]
AKASHA uses `ipfs  v0.4.6`, you might have an old cached version. Close the app if is running then go to appData folder specific to your platform `%APPDATA% on Windows`, `$XDG_CONFIG_HOME or ~/.config on Linux`, `~/Library/Application Support on macOS` and delete entire folder named AKASHA.

**Comment by arobbins** [comment]
@kenshyx 's solution worked for me.

**Comment by ottodevs** [comment]
I had the same problem in macOS AKASHA 0.5.2, I opened `~/.ipfs/version` with my text editor and changed `5` to `4`, save and AKASHA works fine again

Remember to change version to 5 again if you need to use ipfs outside from akasha, or it will prompt you to migrate the data, causing an error.
