### ISSUE TITLE
SIE01Cannot start IPFS service. Check logs for more details.

### ISSUE THREAD

**Issue by jmcmacnz** [AkashaProject/Alpha#94]
Issue #70 looks similar to this however no detail is provided. I also have Parity installed. The issue comes up during initial setup following synchronization.

info
00:12:28
ipfs exited with code: 1, signal: null

error
00:12:28
Error: serveHTTPGateway: manet.Listen(/ip4/127.0.0.1/tcp/8080) failed: listen tcp4 127.0.0.1:8080: bind: address already in use

info
00:12:28
Swarm listening on /ip4/127.0.0.1/tcp/4001 Swarm listening on /ip4/192.168.1.129/tcp/4001 Swarm listening on /ip6/::1/tcp/4001 API server listening on /ip4/127.0.0.1/tcp/5001

info
00:12:27
Initializing daemon...

error
00:12:22
Error: serveHTTPGateway: manet.Listen(/ip4/127.0.0.1/tcp/8080) failed: listen tcp4 127.0.0.1:8080: bind: address already in use

info
00:12:22
ipfs exited with code: 1, signal: null

info
00:12:22
API server listening on /ip4/127.0.0.1/tcp/5001

info
00:12:22
Swarm listening on /ip4/121.98.240.64/tcp/4001 Swarm listening on /ip4/127.0.0.1/tcp/4001 Swarm listening on /ip4/192.168.1.129/tcp/4001 Swarm listening on /ip6/::1/tcp/4001

info
00:12:19
Initializing daemon...

**Comment by kenshyx** [comment]
Check #74

**Comment by jmcmacnz** [comment]
Thank you!
