### ISSUE TITLE
Permanently stuck on empty feed, AKASHA 0.5.2. on Debian 8

### ISSUE THREAD

**Issue by alphanmoon** [AkashaProject/Alpha#98]
Permanently stuck on empty feed and no peers online right now. No issues while registering account. AKASHA is freshly installed (express mode)  on freshly installed Debian 8 (Intel i5, 8GB RAM machine). Network is always up, 100mb/s, wifi infrastusture under regular NAT settings. Nothing special in Debian and net config.  

**IPFS log:** 

LOGS
info
14:32:49
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080 Daemon is ready

info
14:32:49
Swarm listening on /ip4/127.0.0.1/tcp/4001 Swarm listening on /ip4/192.168.1.54/tcp/4001 Swarm listening on /ip4/46.188.51.211/tcp/30040 Swarm listening on /ip6/::1/tcp/4001 API server listening on /ip4/127.0.0.1/tcp/5001

info
14:32:39
Initializing daemon...

![screenshot - 03292017 - 02 54 27 pm](https://cloud.githubusercontent.com/assets/25549734/24453294/ed431f8c-148f-11e7-8ae5-069ac0d01b01.png)

**Geth log:**

LOGS
info
15:10:46
I0329 15:10:46.243025 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 4.691ms ( 0.000 Mg/s). #638324 [ad37c973…]

info
15:10:38
I0329 15:10:38.569148 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 8.473ms ( 0.000 Mg/s). #638323 [d576adcb…]

info
15:10:33
I0329 15:10:33.679562 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 7.911ms ( 0.000 Mg/s). #638322 [ff7a1081…]

info
15:10:26
I0329 15:10:26.708259 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 7.255ms ( 0.000 Mg/s). #638321 [89696068…]

info
15:10:16
I0329 15:10:16.016190 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 4.715ms ( 0.000 Mg/s). #638320 [8ec8d624…]

info
15:09:53
I0329 15:09:53.737442 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 5.068ms ( 0.000 Mg/s). #638319 [38b57c90…]

info
15:09:51
I0329 15:09:51.265167 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 4.649ms ( 0.000 Mg/s). #638318 [d1f20786…]

info
15:09:50
I0329 15:09:50.050149 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 5.236ms ( 0.000 Mg/s). #638317 [eeeb909d…]

info
15:09:39
I0329 15:09:39.596515 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 8.158ms ( 0.000 Mg/s). #638316 [94a6bda1…]

info
15:09:14
I0329 15:09:14.302627 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 8.652ms ( 0.000 Mg/s). #638315 [18147140…]

info
15:08:06
I0329 15:08:06.785099 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 8.709ms ( 0.000 Mg/s). #638314 [fe47598c…]

info
15:07:58
I0329 15:07:58.368871 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 9.876ms ( 0.000 Mg/s). #638313 [f99a913e…]

info
15:07:51
I0329 15:07:51.775999 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 10.196ms ( 0.000 Mg/s). #638312 [02b85177…]

info
15:07:09
I0329 15:07:09.954789 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 8.943ms ( 0.000 Mg/s). #638311 [1c724d4c…]

info
15:06:50
I0329 15:06:50.403742 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 10.203ms ( 0.000 Mg/s). #638310 [876128bf…]

info
15:06:39
I0329 15:06:39.569177 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 11.316ms ( 0.000 Mg/s). #638309 [32158567…]

info
15:06:24
I0329 15:06:24.755098 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 5.276ms ( 0.000 Mg/s). #638308 [c6875112…]

info
15:06:21
I0329 15:06:21.029996 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 8.688ms ( 0.000 Mg/s). #638307 [f5dc8621…]

info
15:06:17
I0329 15:06:17.623107 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 9.624ms ( 0.000 Mg/s). #638306 [1adc2689…]

info
15:06:02
I0329 15:06:02.873847 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 6.328ms ( 0.000 Mg/s). #638305 [fabd436c…]

**Comment by BarefootWarrior** [comment]
Same here. Importing blocks for 48 hours now. Here is the latest log entry:

I1104 08:13:16.698166 core/blockchain.go:1070] imported 1 blocks, 0 txs ( 0.000 Mg) in 7.204ms ( 0.000 Mg/s). #1491619 [7e694a74…]

**Comment by 42piratas** [comment]
Hey @alphanmoon and @BarefootWarrior!

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
